import path from 'node:path'
import vuePlugin from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

/**
 * https://vitejs.dev/config
 */
export default defineConfig({
  root: path.join(__dirname, 'src', 'renderer'),
  publicDir: 'public',
  server: {
    port: 8080,
  },
  open: false,
  build: {
    outDir: path.join(__dirname, 'build', 'renderer'),
    emptyOutDir: true, // to retain the types folder generated by tsc
    cssMinify: false,
  },
  resolve: {
    alias: {
      '@tabler-icons': path.resolve(__dirname, './src/renderer/vendor/tabler/icons'),
    },
  },
  plugins: [vuePlugin()],
})
